Nisq analyzer plugin
UST-QuAntiL/nisq-analyzer-ui pull request #4
Opened 2022-09-18 11:11 UTC by cloudsftp

Implementation of communication with QHana

2022-09-19 12:06 UTC, salmma requested changes
see comments

2022-09-19 12:06 UTC, salmma commented on src/app/components/implementation-view/qpu-selection/qpu-selection.component.ts
> +    if (this.impl) { // TODO: Properly check wheather this.impl comes from qhana plugin
solve TODO

2022-09-19 12:06 UTC, salmma commented on src/app/components/navigation/navigation.component.html
> +        <a *ngIf="!plugin.isPlugin" href="https://platform.planqk.de/my-content">
besides hiding the PlanQK button and the logo, please also change the color of the top bar to one suitable color, as also this shaded bar color is from PlanQK

2022-09-19 13:30 UTC, buehlefs requested changes

2022-09-19 13:30 UTC, buehlefs commented on src/app/components/services/qhana-plugin.service.ts
> +      if (height !== this.qhanaFrontendState.height) {
This if is only relevant if you update the height in the frontend state

2022-09-19 13:30 UTC, buehlefs commented on src/app/components/services/qhana-plugin.service.ts
> +    if (!this.qhanaFrontendState.initialized) {
This does not prevent double execution without the variable being changed somewhere!

2022-09-19 13:30 UTC, buehlefs commented on src/app/components/services/qhana-plugin.service.ts
> +  getUUID(impl: ImplementationItem, uuids: Map<string, string>): string {
please use visibilities like private to hide internal methods. This helps to reduce the API surface and makes it easier to choose the correct method. Also document all public (and also all private) methods.

2022-09-20 07:47 UTC, buehlefs approved these changes

2022-09-20 07:47 UTC, buehlefs commented on src/app/components/navigation/navigation.component.html
> +    <mat-toolbar color="primary" [id]="qhanaService.isPlugin ? 'pa_header' : 'pa_header_pqk'">
Ids should not be changed to achieve styling differences. It is always better to use css classes if styles should change!

2022-09-23 08:58 UTC, buehlefs approved these changes

2022-09-23 08:58 UTC, buehlefs commented on src/app/components/navigation/navigation.component.scss
> +.pa_header {
prefer `-` over `_` in css class names
If you change this, you can merge without requesting another review

2022-09-23 09:19 UTC, merged